name: Docker Build Only Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - 'feature-*'
  pull_request:
    branches:
      - 'nexops/**'

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image tags
        id: vars
        run: |
          BRANCH_SAFE=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "branch_safe=$BRANCH_SAFE" >> $GITHUB_OUTPUT
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            -t myapp:${{ steps.vars.outputs.branch_safe }}-${{ steps.vars.outputs.short_sha }} \
            .