name: Maven CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - feature-*
  pull_request:
    branches:
      - dev
      - feature-*
      - nexops/**

jobs:
  build-test-artifact:
    name: Build, Test, and Artifact with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean compile

      - name: Run Tests
        run: mvn test

      - name: Package Application
        run: mvn package

      - name: Upload JAR/WAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/*.jar
            target/*.war
          if-no-files-found: ignore

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
          if-no-files-found: ignore

      - name: Upload Coverage Reports (if present)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: target/site/jacoco/
          if-no-files-found: ignore
