name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - feature-*
  pull_request:
    branches:
      - dev
      - feature-*
      - nexops/**
  workflow_dispatch:

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build application
        run: mvn clean compile

      - name: Run JUnit tests
        run: mvn test

      - name: Package application
        run: mvn package

      - name: Upload build artifacts (JAR/WAR)
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts
          path: |
            target/*.jar
            target/*.war

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: target/site/jacoco/
